<?php

namespace PropertyBundle\Repository;

/**
 * PinnedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinnedRepository extends \Doctrine\ORM\EntityRepository
{
}
