<?php

namespace PropertyBundle\Repository;

/**
 * Properties_UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Properties_UsersRepository extends \Doctrine\ORM\EntityRepository
{
}
