<?php

namespace PropertyBundle\Repository;

/**
 * Properties_ImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Properties_ImgRepository extends \Doctrine\ORM\EntityRepository
{
}
