<?php

namespace RatingBundle\Repository;

/**
 * Rating_propertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rating_propertyRepository extends \Doctrine\ORM\EntityRepository
{
}
