<?php

namespace RatingBundle\Repository;

/**
 * Rating_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rating_userRepository extends \Doctrine\ORM\EntityRepository
{
}
