property:
    resource: "@PropertyBundle/Resources/config/routing.yml"
    prefix:   /

rating:
    resource: "@RatingBundle/Resources/config/routing.yml"
    prefix:   /

comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   user/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
