property:
    resource: "@PropertyBundle/Resources/config/routing.yml"
    prefix:   property/

rating:
    resource: "@RatingBundle/Resources/config/routing.yml"
    prefix:   rating/

comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   comment/

home:
    path:     /{_locale}/
    defaults: { _controller: AppBundle:Default:index}

recherche:
    path:     /{_locale}/recherche
    defaults: { _controller: AppBundle:Default:recherche}

changeLocale:
    path:     /{_locale}/change
    defaults: { _controller: AppBundle:Default:changeLocale}

property_homepage:
    path:     /{_locale}/property
    defaults: { _controller: AppBundle:Property:index }

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   user/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
